apiVersion: v1
kind: ReplicationController
metadata:
  name: skydns
  namespace: kube-system
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
  template:
    metadata:
      labels:
        k8s-app: kube-dns
    spec:
      containers:
        - name: etcd
          image: gcr.io/google_containers/etcd-amd64:2.2.1
          command:
            - /usr/local/bin/etcd
            - -data-dir=/tmp/data
            - -listen-client-urls=http://127.0.0.1:2379,http://127.0.0.1:4001
            - -advertise-client-urls=http://127.0.0.1:2379,http://127.0.0.1:4001
            - -initial-cluster-token=skydns-etcd
          volumeMounts:
            - name: etcd-storage
              mountPath: /tmp/data
        - name: kube2sky
          image: gcr.io/google_containers/kube2sky-amd64:1.15
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 3
            timeoutSeconds: 1
          args:
            - --kube-master-url=http://172.17.0.1:8080 # 使用 Docker 网桥的默认网关，本节点上的容器能够以这个IP访问 API server
            - --domain=cluster.local
        - name: skydns
          image: gcr.io/google_containers/skydns:2015-10-13-8c72f8c
          args:
            - -machines=http://127.0.0.1:4001
            - -addr=0.0.0.0:53
            - -ns-rotate=false
            - -domain=cluster.local
          ports:
            - name: dns
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
        - name: healthz
          image: gcr.io/google_containers/exechealthz:1.0
          args:
            - -cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null
            - -port=8080
          ports:
            - containerPort: 8080
      volumes:
        - name: etcd-storage
          emptyDir: {}
      dnsPolicy: Default

