apiVersion: v1
kind: Pod
metadata:
  name: limitrange
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 200m    # 调整小，创建会失败，命令输出会显示详细出错信息
      limits:
        cpu: 300m
